"""Banco de ideas y copy para redes sociales (Instagram, Facebook, TikTok)."""

SOCIAL_CONTENT = {
    "captions_productos": [
        "Una cartera Mishki para los días lentos y los planes sin apuro. Tejida a mano en algodón crudo.",
        "Chaleco Quillay: 36 horas de tejido, una vida entera de uso. ¿Tu favorito de la temporada?",
        "Bandolera Amaru en terracota, porque hay colores que no se gastan. Edición limitada de 8 piezas.",
        "Bufanda Trenza: lana merino, dos agujas y mucha paciencia. Una pieza que abriga sin pesar.",
        "Gorro Andino con motivos contemporáneos. Hecho a mano, sí, pero pensado para hoy.",
        "Neceser Luna: pequeño, dorado, perfecto para esenciales o como cartera de noche.",
        "Tote Pacha: amplio, firme, listo para acompañarte de lunes a domingo.",
        "Chaleco Raulí, en alpaca y merino. El abrazo textil que se merece tu otoño.",
        "Tres ovillos, cien horas y una pieza única. Así nace cada Unika.",
        "Encargos personalizados abiertos: cuéntanos tu pieza soñada y la tejemos contigo.",
    ],
    "ideas_reels": [
        "Time-lapse de un chaleco tejiéndose en 30 segundos.",
        "Antes y después: ovillo crudo → cartera terminada.",
        "Manos tejiendo en cámara lenta + voz en off contando la historia de la pieza.",
        "Detalle macro del punto trenzado en loop hipnótico.",
        "Día en el atelier: 60 segundos del proceso real de un lunes.",
        "Tres formas de usar la misma cartera Mishki.",
        "Cómo elegimos las fibras: visita a una pequeña hilandería local.",
        "Unboxing artesanal: empaque en papel kraft, hilo encerado y etiqueta cosida.",
        "Cliente real recibiendo y abriendo su pieza por primera vez.",
        "Reto: tejer un detalle simple en 60 segundos, mientras explicamos por qué tomó 12 horas el original.",
    ],
    "frases_marca": [
        "Hecho a mano, hecho con tiempo.",
        "Lo único, como manifiesto.",
        "Tejemos despacio para que dure mucho.",
        "Una pieza, una tejedora, una historia.",
        "Fibras nobles, manos honestas.",
        "Sin prisa, sin copia, sin serie.",
        "Lo bien hecho no se apura.",
        "Vestir lento también es elegir bien.",
        "Cada nudo es una decisión.",
        "Tu cartera no es de todos: es solo tuya.",
    ],
    "publicaciones_lanzamiento": [
        "Carrusel: la nueva colección 'Tierra' está abierta. 12 piezas únicas, numeradas y listas para encontrar dueña.",
        "Reel: time-lapse del proceso de la pieza estrella de la colección.",
        "Post estático: foto editorial + frase de marca + fecha y hora de apertura.",
        "Historia con cuenta regresiva: 24 horas antes del lanzamiento, mostramos detalles uno a uno.",
        "Carrusel post-lanzamiento: piezas vendidas, agradecimientos a las primeras clientas y guiño a la próxima colección.",
    ],
    "publicaciones_proceso": [
        "Selección de fibras: video corto desde la hilandería, contando por qué elegimos esa lana.",
        "Carrusel del paso a paso: boceto → muestra de tejido → pieza terminada.",
        "Reel manos tejiendo + texto en pantalla con la cantidad de horas que toma una cartera Mishki.",
        "Post sobre las tejedoras: foto de manos + nombre + cuántas piezas hizo esta temporada.",
        "Historia diaria: 'hoy en el atelier...' mostrando avances reales, sin filtros.",
    ],
    "publicaciones_venta_directa": [
        "Carrusel 'piezas disponibles esta semana' con precio, talla y link a la tienda.",
        "Reel de 15 segundos: tres carteras nuevas + CTA 'reserva por DM antes de que se vayan'.",
        "Historia con encuesta: '¿cuál se va contigo?' y link directo a pagar.",
        "Post de cliente real usando su pieza, con CTA 'consigue la tuya en bio'.",
        "Anuncio de pedidos personalizados abiertos por 72 horas + cupos limitados.",
    ],
}
